@startuml DataWarehouse

skinparam ComponentStyle uml2

' left to right direction
' top to bottom direction

cloud "Оперативная OLTP БД компании" as cloud_oltp_orders #LightBlue {

}

Actor "Внешний\nПользователь" as extuser
'bc4
Actor "Прием\nзаказов" as extuser4 #Tomato

frame "Хранилище\nтипа Data Lake" as frame_dlstor {

    frame "Витрины" as frame_dlstor_dm #Gold {
        component controller_extuser_reports [
            Асинхронное управление
            отчетами пользователя
            (заказ, выдача по событию завершения)
        ]
        database "Реляционная БД\n" as db_dm {
            component report_daily_plan [
                Отчет для ежедневного
                планирования в диспетчерской
                Содержит распарсенные данные за неделю
            ]
            component report_extuser_reports [
                Отчет заказанных
                пользователем отчетов
            ]
        }
        component batch_report_daily_plan_refresh [
            **Batch**
            ----
            Обновление отчета
            для планирования
            ----
            Периодичность: Ежедневно
        ]
        component batch_extuser_report_order [
            **Batch**
            ----
            Заказ сложного отчета
        ]
        component batch_extuser_report_delivery [
            **Batch**
            ----
            Получение заказанного отчета
            и его очистка из БД
        ]
        'bc4
        component report_drivers_online #Tomato [
            Отчет
            ----
            Таксисты на линии
        ]
        'bc4
        component control_report_drivers_online #Tomato [
            Управление отчетом
        ]
    }

    frame "Обработанные данные" as frame_dlstor_stage #LightGreen {
        database "Реляционная БД\n" as db_stage {
            [Таблица заказов такси\nза неделю] as tbl_staged_orders_week
        }
        component batch_tbl_orders_week_refresh [
            **Batch**
            ----
            Оперативное обновление stage-данных за неделю
                - добавление нового из источника
                - удаление в приемнике всего старше недели
        ]
        'bc4
        database "In-memory БД" as db_drivers_online #Tomato {
            component tbl_drivers_online [
                Таксисты на линии
                ----
                Код области
                Код автомобиля
                Краткая информация
            ]
        }
    }

    frame "Сырые данные" as frame_dlstor_raw #LightGray {
        database "БД Типа Key-Value" as db_raw {
            [**Таблица заказов**\n**за все время**\n----\n**Ключ**\nДата поездки\nНомер заказа\nГосномер авто\nКод страны\n----\n**Данные**\nДанные геолокации\nДругие данные] as tbl_raw_orders
        }
        component batch_raw_load [
            **Batch**
            ----
            Загрузка сырых данных
            ----
            Периодичность: Несколько раз в день
        ]
        'bc4
        component batch_driver_status_proc #Tomato [
            **MicroBatch**
            ----
            Обновление таблицы
            В режиме change data capture
        ]
    }

    cloud_oltp_orders --> batch_raw_load

    batch_raw_load --> tbl_raw_orders

    tbl_raw_orders --> batch_tbl_orders_week_refresh
    batch_tbl_orders_week_refresh --> tbl_staged_orders_week

    tbl_staged_orders_week --> batch_report_daily_plan_refresh
    batch_report_daily_plan_refresh --> report_daily_plan

    extuser -right-> batch_extuser_report_order
    batch_extuser_report_order --> controller_extuser_reports
    
    controller_extuser_reports <-- tbl_raw_orders
    controller_extuser_reports <--> report_extuser_reports

    controller_extuser_reports --> batch_extuser_report_delivery
    batch_extuser_report_delivery -left-> extuser


    'bc4

    (Водитель\nна линии) as driver_online #Tomato
    (Водитель\nснялся с линии) as driver_offline #Tomato
    (Водитель\nпереместился\nна другую линию) as driver_moved #Tomato
    (выборка\nданных) as select_drivers_online #Tomato
    (insert/update/delete) as insupddel_drivers_online #Tomato
    
    cloud_oltp_orders --> driver_online
    cloud_oltp_orders --> driver_offline
    cloud_oltp_orders --> driver_moved

    driver_online --> batch_driver_status_proc : stream ins
    driver_offline --> batch_driver_status_proc : stream del
    driver_moved --> batch_driver_status_proc : stream upd

    batch_driver_status_proc --> insupddel_drivers_online
    insupddel_drivers_online --> tbl_drivers_online

    extuser4 <--> control_report_drivers_online : онлайн-запрос отчета
    tbl_drivers_online --> select_drivers_online
    select_drivers_online <--> control_report_drivers_online
    control_report_drivers_online <--> report_drivers_online : формирование отчета

}
@enduml