= Домашнее задание №2

== Постановка задачи

[source]
----
Строим свою архитектуру
Цель: В данном домашнем задании от участников курса ожидается небольшой архитектурный документ ( желательно - не более 3-х страниц).

Выберите интересный сервис (Twitter / Uber / Linkedin / ваша организация или собственный проект) и разработайте для него архитектуру аналитического хранилища данных.

Опишите возможные требования к хранилищу, источники и архитектуру хранения.

Приведите пример бизнес-кейса, который можно решить с помощью выбранной вами архитектуры.
В решении обязательно должна присутствовать архитектурная схема вашего решения, которая должна объяснять откуда к вам поступают данные, как вы планируете их хранить и как вы планируете их отдавать для решения бизнес-кейса.
Описание архитектуры - это стандартное задание на архитектурных собеседованиях для Data Engineer.
Выполнив данное задание, вы сможете в будущем воспользоваться этими знаниями для того, чтобы качественно и продуманно создавать дизайн для аналитического хранилища данных или понимать как ваше data-driven приложение ложится в экосистему вашей организации. 

Для рисования схемы советуем использовать бесплатный сервис draw.io
Разместите ответ в виде документа Google Docs и поделитесь ссылкой.

Критерии оценки:
1.Факт свершения действия - архитектурный документ предоставлен на ревью
+1 балл

2. Степень выполнения ДЗ
+1 баллов – бизнес-кейс не описан, но приведены источники данных и разработана архитектура и описана архитектурная схема
+2 балла – источники и бизнес-кейс описаны, разработана архитектура и приведена архитектурная схема

3. Способ выполнения ДЗ
+1 балл – документ выполнен качественно, но архитектурная схема недостаточно детальна
+2 балл -- документ выполнен качественно, архитектурная схема содержит детальное описание процесса

Рекомендуем сдать до: 08.12.2019
----

== Решение

=== Компания Uber, аналитическое хранилище для сбора информации по заказам такси.

В это хранилище будут поступать и там храниться данные по заказам
от всех автомобилей, зарегистрированных в Убер.

==== Аналитическое хранилище данных

===== Требования

* 1. Хранение исторических данных за большой промежуток времени (10 лет и более)
* 2. Быстрый доступ к информации за последнюю неделю для ежедневного планирования
* 3. Доступ к остальной информации в режиме заказа отчетов (заказал сейчас, получил через какое-то время)

===== Источники

* Данные от OLTP-БД: заказы на поездки
  ** Ключевая информация
     *** Номер заказа
     *** номер автомобиля (+код страны)
     *** timestamp заказа)
  ** Остальная информация по заказу
     *** информация от системы геолокации +
         может быть различной в зависимости от используемых аппаратных средств (gps, glonass...)
     *** остальное +
         (может добавляться или меняться со временем и развитием компании)

===== Архитектура хранения

Архитектуру выбираем типа Data Lake, поскольку будем хранить всю слабоструктурированную информацию о заказах на нижнем уровне (raw), парсить и преобразовывать ее на среднем (stage) и отдавать в виде решений для бизнес-кейсов на витрины.

Собственно архитектура (кликабельна):

image:http://www.plantuml.com/plantuml/png/fLXTRnDN4xxVNt445u3rMaYlk49LHMabL9MgbOhQ2u9M6-y9iLZlMkjZQ8IGyb6QLa59cwQgX5GeLBrtJ4nCoCTVEESVTUPPhxCVFbxNM08xU-QPcVFCnunzewEyM7LRWVZCKzvtNYoNesv7EaxdGJDiUx7N4fz6hNOKob1zerO2AKZs_uvpIGHoIGaLYRXvVra9lndBXcf68PsegCq7Yv5IKIjpuZI2gEkB2_g5FjC3iwfxPbqFTL-VqASTyTNjEryB_QlU4_f8d-fZ4khHqL0FBmYl8m1seq2rtIZsPTmH5s-pwPj1Luh7ZlF4SJvfg2Wc_Ri46vYV07wt4EgNfEwzUQOFwRqFgmF-6shbzuhk6pkN5XlNnWfUadD34Zecy25vSKJ_0Cv2hecBTwAMfoB7MIAU9E7-8LpYytizD3_hmKA8Az9DmA-uxJsGq064wmSTCiZU2tgbMdO9kmuFJinMIThrM-BYhIZm2IP6hqOQ8leKgZWA0Xcx8pVTMBQZM7N4tLGSB_sBMOE5fsJfb7m-eVy7mcpeCroYJrSOu2g3FEwKVDiaUjT9w5WFXJwRoEvE3dNvdCR_2TqtM_g093Tr3t1XrWYxRxQOBBCj8Dpd5A4WmWcpSsMixzxuaq-KBdeTvkolnAZvKGzn6wGKicaX18N-8X6NKbQYBU78zRrciEAs0oyii8MRlqXlBlG16nDayotzE-1qqtqm-4QVbe5dn2NI0bJtay-CxvCc-hI6Ue1okl8QqlzTMSqhUdo0mddB6I8uJi3s60MYA64eY4nk-WV85F3m01njvnJVcqg89OTih8nZd9etJulobdJXMikc5XrPt7mo8UaNFTLOTainf2TBiUmi5xokrMwoVAsMUrgdbvE_cDv7I3ELaCl-l3GomXhg2bCl4LNANAJ39firQsJfsNMXVo_cMB4GobGKmfRqopbP-2EDAHVfU_BmRPhdaycOsIbV1is7CbwPqw-afs-G_JGsnVIRvYLK30LX4n4I63BZZAS3VOZMCU5I61Fs_X7pbJfk50RDKARp0JUSL34LLtpDz-4kZLpO4jpK14-MP2fQlBCF1VS_UVbtUH3aA_IuuC2J_1IZyW5-dq7qFgavbOSRhIFtvMYotugb3CNZUTizL1Kw_bsGkiya4hOdyjDTm55GlX2M-kOzrgiMWqInFzf2t4TIFfYXEn4mY_ZWtbJSe4uHdWaj2zxMpratJoj60YnIcA2j47yeJmiBPOBav0A2254vGPVPWFcCdhv0Tc77Ie1uobCCkg6qbyp_ZAVsf2_doETXlILRKRo2j4YJmfBxbhq0uIv0ae3DKwZsU4BBSsx_Y27F430mj4fHN98YXFmG2rTPTfGXHwWER7i_KAXM2TNZqW76EcIB1VsAScTrXXAElKVZ0lPM9jSljlpNeytu2xbI_zQZDJuD4caercsjDhLoQxM5a4IGryWYVblbx38xVCQCG-8vfxlPv6Tw3-GaAoY97jArZb3vVu9Ogg_SJA63ttWkemXmF0u37I4ko5icdRd9MDqxvokndEs7RyZsAKRhKH8M-B17N6_GsR30Tzg5cAHHGwdkFX0E8i__W2NW3HmwP2VfciW5z99COvb_oo7A1rXyiHlokm2DXwCTUK06dbbgttff52v62YqURZkE6fPPLwjzsMp4qVnheLa_pqspbPVV5KX4MjavQKHZsGllIzI2Q7XjrOtbv3bQ_hvRhtzS22Sa2yyWLaWGYEMVGMpgQ09egWHqM2OYeordW5Nix81No41FwHIMq-_eeewV9qZElXX3tduCA_QlrK3ZFxkC-AXUBz1VYSZShMYn2alGwIit54oL4FL0BZ5jetC7HfDomwVBUZUfu_J7b8MmCFMke9cZ10lJrgQ0MwlPeSzhPeTQZ4tNqj8ioaOBqW2T6hCqKPpwUP3qLxDXjiU6p7RMK2jwAFsy6VnoiOyHUeI1a6b-W7Pa81ks3JlHqGo9JtMrswOM8A_w150IM3gWX_HW6jpU6l9SLyc1nza4mGEYdZS16MkdlIuwAfPUYwy5RDxiZ61Y0-2iApD2YKiuRHM57XlfGDeEWIolXhdESmqbNF7Lwxh0jnV-oU2TFgbZsw2zcETYwNih39Rzc9no04mygNOBu0h7eSHsftJ9pFy8KlprX7wmlI53lziA_WK0[Схема]


===== Пример бизнес-кейса

Аналитические отчеты

* 1. Распределение плотности заказов по районам за последнюю неделю +
  Реализуется при помощи батча "Обновление отчета для планирования"
* 2. Статистика заказов по будням и выходным за год +
  Реализуется при помощи батча "Заказ сложного отчета" +
* 3. Статистика заказов на новогодние праздники за последние 10 лет
  Реализуется при помощи батча "Заказ сложного отчета"

Возможна реализация п.2 как в п.1, для этого необходимо добавить еще одну оперативную витрину и обновляющий ее каждый день батч в режиме CDC.

===== Дополнительный бизнес-кейс #4

* В отделе прием заказов требуется оперативная информация о всех таксистах онлайн в данном районе

===== Решение

* Организация приема данных в режиме стриминга
* Буферизация данных в ин-мемори таблице
* Оперативная моментальная выдача по запросу +
  либо постоянное отображение (запрос, скажем, раз в секунду)

На схеме соответствующие добавленные компоненты добавленчы и подсвечены красным цветом
