= Домашнее задание №2

== Преамбула

Попытался сделать задачу сугубо на основе занятия №2 Антона Задорожного и того, что я из него понял и усвоил.

Поскольку многими понятиями я до этого не владел или знал только понаслышке,
скорее всего, ДЗ получилось далеким от того, что требовалось.

Просьба все, что нужно уточнить, дополнить или переделать, написать мне подробно.

Хочу набрать все необходимые баллы самостоятельно.

ДЗ выполнено при помощи asciidoc+plantuml.

== Постановка задачи

[source]
----
Строим свою архитектуру
Цель: В данном домашнем задании от участников курса ожидается небольшой архитектурный документ ( желательно - не более 3-х страниц).

Выберите интересный сервис (Twitter / Uber / Linkedin / ваша организация или собственный проект) и разработайте для него архитектуру аналитического хранилища данных.

Опишите возможные требования к хранилищу, источники и архитектуру хранения.

Приведите пример бизнес-кейса, который можно решить с помощью выбранной вами архитектуры.
В решении обязательно должна присутствовать архитектурная схема вашего решения, которая должна объяснять откуда к вам поступают данные, как вы планируете их хранить и как вы планируете их отдавать для решения бизнес-кейса.
Описание архитектуры - это стандартное задание на архитектурных собеседованиях для Data Engineer.
Выполнив данное задание, вы сможете в будущем воспользоваться этими знаниями для того, чтобы качественно и продуманно создавать дизайн для аналитического хранилища данных или понимать как ваше data-driven приложение ложится в экосистему вашей организации. 

Для рисования схемы советуем использовать бесплатный сервис draw.io
Разместите ответ в виде документа Google Docs и поделитесь ссылкой.

Критерии оценки:
1.Факт свершения действия - архитектурный документ предоставлен на ревью
+1 балл

2. Степень выполнения ДЗ
+1 баллов – бизнес-кейс не описан, но приведены источники данных и разработана архитектура и описана архитектурная схема
+2 балла – источники и бизнес-кейс описаны, разработана архитектура и приведена архитектурная схема

3. Способ выполнения ДЗ
+1 балл – документ выполнен качественно, но архитектурная схема недостаточно детальна
+2 балл -- документ выполнен качественно, архитектурная схема содержит детальное описание процесса

Рекомендуем сдать до: 08.12.2019
----

== Решение

=== Компания Uber, аналитическое хранилище для сбора информации по заказам такси.

В это хранилище будут поступать и там храниться данные по заказам
от всех автомобилей, зарегистрированных в Убер.

==== Аналитическое хранилище данных

===== Требования

* 1. Хранение исторических данных за большой промежуток времени (10 лет и более)
* 2. Быстрый доступ к информации за последнюю неделю для ежедневного планирования
* 3. Доступ к остальной информации в режиме заказа отчетов (заказал сейчас, получил через какое-то время)

===== Источники

* Данные от OLTP-БД: заказы на поездки
  ** Ключевая информация
     *** Номер заказа
     *** номер автомобиля (+код страны)
     *** timestamp заказа)
  ** Остальная информация по заказу
     *** информация от системы геолокации +
         может быть различной в зависимости от используемых аппаратных средств (gps, glonass...)
     *** остальное +
         (может добавляться или меняться со временем и развитием компании)

===== Архитектура хранения

Архитектуру выбираем типа Data Lake, поскольку будем хранить всю слабоструктурированную информацию о заказах на нижнем уровне (raw), парсить и преобразовывать ее на среднем (stage) и отдавать в виде решений для бизнес-кейсов на витрины.

image:http://www.plantuml.com/plantuml/svg/fLTTRnj557tVNp7g4rZuXKU4KFbuen9885wQQBN9RccKzTfQhobH5QbEL09Ar409GghKbbRYtN7iU9iFvo_S-KUSEHw7tR6zXcGhr-kPU-wzS-wPEvExxIn8iquZzhpsvaRI2jAWeJvlDbhD94goRxAjE5AO_T3prkDc9rHtv9LSoL0_aPxUaLpwSectG_NLlM-_LlAR72avax5SmAY7gLpoEofeAuBzPfor_6OQHcbRFVQyRS_xT3rhfd3w7BP3_JCHxrOIUGqVv_f0HlZkCzJG_AQlwCUiquvIptk0N2E0_pRP47ekkVv5Xegf8GFrHP05wbwm6H59W1_6RHCK2IWyKoVF0Ts1ermkzVwCjHys053sMP_oWxSaIvjn7AM-JSjFerOppThg_jISZ_ogk_Jz5376Seb_OvFehbmn-pvo7t8Dmp9kZApsmCqEZ2uaLt8rbvh34kezpFRa39_H1qhwUby6iDoJ7k5ATu4zrlk69lrCqRXlYeeAC0bz-FwrlzNhjn1ahWLjmzPVaw3w9ycv6eg0zLz9I5wuLgBCeMt2aHy66_6Mtug3n66BAtyrNRcIWGcc4FCKdu7HYlJ9u8cCPu5Nu99w8DLz-mvy7vxmrgM2wHnBxbAmxsRTlC7mW58_DTfGfax4zWoAH44gAA8XT_g3P2fcE217pqgELwi9SJLKpSfrZQVXzLFNVe5SyBaeIWjJ2zBSdYFwjI1RV-ZFr10Z3zAe_T39kbRxpDZNQgNHEXwll30vPaaBEw6a_h8r5R6mr4j2lMPLeLpAOS-4rLr4ElX8oH-knjoDC4k5KxP9XxiX2tzEQseswJaoF9tgt27Z_oOLHl763r6wTREyR4FUHNnR6qT-bLdoCRrhQ4rWa1l63HuJCcBhS1QrNMxGq0SxvJ7Wy3rtzytsRHnltqVgyGrxc0ldSr_UCWqSDi3sYaH0Weh9dPbklvBCD8DLupTRYoUEGtiO-e-YQFC_R3a0YuXRRpZt81zpoytPXyosRfbcerdIvnWHfQ6tNicNTKwrsDfJ2qOLD06LStpfNOOl-EahdfsvQMOJ84TrrygCJdkJGwsGgUJLEdkZzu5PhgmqU3HVLxm4lRKNa2-ZhVftGTo9hA88S_HKgrKggbPRIM12lhawy_N4h5eVcZbJMLgyC6NGUsPCZbZMoNaFqn7MSaP5lkJj37KlRM1C_6wQ88jZfr4sKnLClJ2Tadno1uAGGjIZVqcoaGjxymInn-nZ2CITbXiJ4BoBkTmXURex34bMwCjt1OtZPX3UekEUCA6HIHBBf02eyOBWRt6alCGSRnayYF6jIEF8NaY6270mLvEprsP4_iHPDYsTCPevHDAiF4QpojP2KAK5VIpeQ4JFdoDioKM2y2Ksz3CpEubiJq2QB3weQRfmckYAQpxH_6-nZVguNdUONueeBCkDk0mBQFKLW0ugBUZ3pfc_q-v6ITXfnFy0[Схема]


===== Пример бизнес-кейса

Аналитические отчеты

* 1. Распределение плотности заказов по районам за последнюю неделю +
  Реализуется при помощи батча "Обновление отчета для планирования"
* 2. Статистика заказов по будням и выходным за год +
  Реализуется при помощи батча "Заказ сложного отчета" +
* 3. Статистика заказов на новогодние праздники за последние 10 лет
  Реализуется при помощи батча "Заказ сложного отчета"

Возможна реализация п.2 как в п.1, для этого необходимо добавить еще одну оперативную витрину и обновляющий ее каждый день батч в режиме CDC.