= Домашнее задание №2

== Постановка задачи

[source]
----
Строим свою архитектуру
Цель: В данном домашнем задании от участников курса ожидается небольшой архитектурный документ ( желательно - не более 3-х страниц).

Выберите интересный сервис (Twitter / Uber / Linkedin / ваша организация или собственный проект) и разработайте для него архитектуру аналитического хранилища данных.

Опишите возможные требования к хранилищу, источники и архитектуру хранения.

Приведите пример бизнес-кейса, который можно решить с помощью выбранной вами архитектуры.
В решении обязательно должна присутствовать архитектурная схема вашего решения, которая должна объяснять откуда к вам поступают данные, как вы планируете их хранить и как вы планируете их отдавать для решения бизнес-кейса.
Описание архитектуры - это стандартное задание на архитектурных собеседованиях для Data Engineer.
Выполнив данное задание, вы сможете в будущем воспользоваться этими знаниями для того, чтобы качественно и продуманно создавать дизайн для аналитического хранилища данных или понимать как ваше data-driven приложение ложится в экосистему вашей организации. 

Для рисования схемы советуем использовать бесплатный сервис draw.io
Разместите ответ в виде документа Google Docs и поделитесь ссылкой.

Критерии оценки:
1.Факт свершения действия - архитектурный документ предоставлен на ревью
+1 балл

2. Степень выполнения ДЗ
+1 баллов – бизнес-кейс не описан, но приведены источники данных и разработана архитектура и описана архитектурная схема
+2 балла – источники и бизнес-кейс описаны, разработана архитектура и приведена архитектурная схема

3. Способ выполнения ДЗ
+1 балл – документ выполнен качественно, но архитектурная схема недостаточно детальна
+2 балл -- документ выполнен качественно, архитектурная схема содержит детальное описание процесса

Рекомендуем сдать до: 08.12.2019
----

== Решение

=== Крупная транспортная компания-перевозчик, например DHL

==== Аналитическое хранилище данных

===== 1. Требования

1. Хранение исторических данных за большой промежуток времени
2. Аналитика
  ** за небольшой промежуток времени (день-два) (для составления плана транспортной логистики на след. день)
  ** за большой промежуток времени (статистические месячные, годовые расчеты)

===== 2. Источники

* Данные от OLTP-хранилищ (БД-источники)
* Представляют собой оперативные данные обо всех транспортных средств компании +
  Возможно, состоит из нескольких БД-источников, различных по оперативности
  ** геолокация
  ** информация о наряде
     *** место отправления, назначения, грузы
  ** текущее состояние
     *** отбыл, прибыл, на разгрузке, погрузке, простой, ожидание груза и пр.
  ** информация о загрузке
     *** заполненность кузова, виды грузов и пр...

Нам важно не нагружать сильно БД источника, поэтому

* если БД источника будет что-то вроде Оракла, то можем забирать просто архивные журналы
  транзакций (архивлоги)  и накатывать их у себя в какой-нибудь промежуточной оракловой БД,
  а затем перемещать в более подходящую БД либо оставлять в Оракле. +
  Это вообще не будет давать никакой дополнительной нагрузки на БД источника.

* В другом случае можно просто несколько раз в сутки максимально быстро выкачивать информацию за определенный период без какой-либо сложной нагрузки на БД источника.

===== 3. Архитектура хранения

Если данные сугубо с нмеа, тогда дата лейк норм, сырые там, все такое...
Если как описал в последнее время, то.....

Архитектура типа Data Lake

* Нижний слой, сырые данные +
  Получаем согласно предыдущему подразделу 2 (Источники)
* Средний слой +
  Здесь мы сырые данные в формате NMEA парсим, выделяем координаты, высчитываем локальное время, скорость, идентифицируем транспортное средство, связываем со справочниками, возможно, преобразуем в форматы гугл мапс и пр.
* Верхний слой, дата март +
  Различные витрины
  ** Логистические отчеты за сутки для планирования загрузок
  ** Витрины статистических отчетов за месяц, год по пробегу, расходу топлива, средней скорости,
     охвату территории, пересечению границ и пр.
  ** Заказные отчеты по требованиям клиентов в их личных кабинетах +
     клиент заказывает отчет, он считается и поступает клиенту через какое-то время

===== Пример бизнес-кейса

Отчет для логистики, планирования перевозок на следующие сутки