@startwbs

skinparam defaultTextAlignment center
skinparam ActivityBackgroundColor Gray

header Домашнее задание

* Дата инженерия

** Топ потребностей бизнеса
*** Производство и добыча: IIoT, Отчетность, Продажи
*** Ритейл: Продажи, CRM, Аналитика, Логистика
*** Банки: Скоринг, Антифрод, CRM, Отчетность, РС*
*** Телеком: CRM, РС*, Аналитика
*** Медиа и Веб: Реклама, CRM, Аналитика
*** Рекомендательные системы
*** Еще сценарии использования
**** Выписки по счетам
**** Управленческая отчетность, аналитика
**** Мониторинг Media, Графы связей
**** ClickStream, Веб-аналитика
**** Real-time скоринг, антифрод, маркетинг
**** Рекомендательные системы
**** IIoT: Мониторинг, Прогнозирование


** ключевые технологии и умения
*** Карта навыков
**** <&heart>\nDatabases: SQL & NoSQL
**** Operations
**** DevOps
**** Software Development
**** Cloud Platforms
**** Big Data Tools
**** Data Warehousing
**** Коммуникация
**** Понимание бизнеса
**** Computer Science
**** ML + BI


** Понять для себя\nгде и чем бы вам\nхотелось заниматься

** анализ рынка\n"Инженер Данных"
*** *Одесса
*** Украина
*** РФ
*** USA
*** EU

** Фиксация целей\nна процесс обучения

@endwbs