@startwbs

centerheader
= Домашнее задание
endheader

legend top left
* При поиске вакансий использовал фразу +
  "Data engineer"
* Отметки
** <&heart> - Нравится, хотелось бы заниматься
** <&check> - Есть знания и опыт
** <&plus> - Есть какие-то знания
endlegend

* Дата инженерия

** Топ потребностей бизнеса
*** Производство и добыча: IIoT, Отчетность, Продажи
*** Ритейл: Продажи, CRM, Аналитика, Логистика
*** Банки: Скоринг, Антифрод, CRM, Отчетность, РС*
*** Телеком: CRM, РС*, Аналитика
*** Медиа и Веб: Реклама, CRM, Аналитика
*** Рекомендательные системы
*** Еще сценарии использования
**** Выписки по счетам
**** Управленческая отчетность, аналитика
**** Мониторинг Media, Графы связей
**** ClickStream, Веб-аналитика
**** Real-time скоринг, антифрод, маркетинг
**** Рекомендательные системы
**** IIoT: Мониторинг, Прогнозирование

** ключевые технологии и умения
*** Карта навыков
**** <&heart>\nDatabases
***** <&check>\nSQL
***** NoSQL
**** <&plus>\nOperations
**** DevOps
**** <&check>\nSoftware Development
**** Cloud Platforms
**** Big Data Tools
**** Data Warehousing
**** Коммуникация
**** Понимание бизнеса
**** <&plus>\nComputer Science
**** ML + BI

** Понять для себя\nгде и чем бы вам\nхотелось заниматься

** анализ рынка\n"Инженер Данных"
*** К-во предложений
**** Одесса
***** LinkedIn
****** 0 результатов по поиску "Data engineer"
**** Украина\n
***** jobs.dou.ua по городам\n[[link:https://jobs.dou.ua/vacancies/?category=Data+Science&search=Data+engineer&descr=1 link]]
****** Киев 42
****** Одесса 10
****** Львов 10
****** Харьков 10
****** Днепр 4
****** Черновцы 3
****** Винница 2
****** Запорожье 1
****** Херсон 1
****** Сумы 1
****** Хмельницкий 1
****** удаленная работа 10
***** LinkedIn
****** 277 результатов по поиску "Data engineer"
**** РФ
***** LinkedIn
******  64 результата по поиску "Data engineer"\nВозможно, столь малый результат из-за блокировки этого сайта в РФ
***** HeadHunter [[https://hh.ru/search/vacancy?area=1&st=searchVacancy&text=Data+engineer link]]
****** Россия 1005 предложений
****** Москва 455 предложений
****** Санкт-Петербург 261 предложение
**** EU
***** LinkedIn
****** 26 848 результатов по поиску "Data engineer"
**** США
***** LinkedIn
****** 37 731 предложений\nДумал, будет больше\nпо отношению к Европе

** Фиксация целей\nна процесс обучения
*** Пока не выполнена

@endwbs