= Домашнее задание 1

== Оформление этого ДЗ

Использовал предпочитаемый мной на сегодняшний день формат ведения документации: *_asciidoc+plantuml+git_*

== Исходная постановка

[source]
----
Домашнее задание: анализ рынка Инженер Данных: РФ, USA, EU
Топ потребностей бизнеса, ключевые технологии и умения
Понять для себя, где и чем бы вам хотелось заниматься
Фиксация целей на процесс обучения
Рекомендуем сдать до: 03.12.2019
----

== Решение

* После прослушивания вводной лекции по DE прочитал еще несколько статей и примерно составил впечатление о том
  ** что на сегодняшний день представляет из себя эта профессия
  ** с какими инструментами там работают
  ** какие задачи решают
  ** какие умения требуются
* Выделил в структурную схему WBS на основе материалов лекции
  ** Топ потребностей бизнеса, для которых нужны DE
  ** Ключевые технологии и умения
* Окинул ее взглядом, много думал (С)
* На основании предыдущего пункта добавил в эту структуру собственно домашее задание

=== Схема WBS

image:http://www.plantuml.com/plantuml/svg/fLTTRnD757tthnZn4BN19WG2GLPJ41yIaK9fWPQ7X8UDlSG6PpVohg6yaOH0gr12sw1MXPPIMhMFnc79nadilp3pZthEpdNOh6nG2m_8U-VUE_UUU-RCv5GGElNmzcoGovLSBtJh5TSfk_NSXDBhkgDtTDDyetTrf2EbDtLJlzPDVCOwohbUMNnpDNSENohq5rJDlHxcXfL-RkxgMEakSiHcKRSPtq9ic_4mn7fB9Ilqs3OFaRoJE6mhSm-nJRrfbjN1d587pZgXernlhkgvRlq0a_zcbb1PXF_REiuD3wjFXYekslXK5PJ-DObk8VcIMJHhUMLMT0UkaTxM7LWUAltAhA8RwGGjmlCXVMsgKiKjtKnIFO4HI_JTjTvcJR6jZkwQLRDa_HTgZM2_Evji4wG2zkti2oTi5guSErddvhg9f5X-eoD2ZVhfoEIC8YPOtbJchbd59vBFU0Vqp-a09gBhBgfQ0KGC_QMWMzoyYtoHVitk9G3OquL0mXwXwaNTf0McgQftqorFUlpazs75S0w3KsAjR4ctaj6cvckMiuEIBLvY3GDXWonSjhdXpmQ7odxZKCEHJ1kw0xzEGh2T6MzwkePAYfKmN0YA8oCf_v5RJidnIbKt63bPSa9tpg_VcU3M1o_3w9NSeG1SA5MihLVEKDaDIlM9KSMqrwv9Uq29Oq8xOqTeoeAYHW_lcP-2f2ssdZR-1JpkOg6TNLZdO8Yz6jkp_SrHmGvNSnyKFBgtyWFXIGXo7vk-BUKdWD4LODvWcqYDfhP6DhE8bTsKzGK6jOFSQJyS5GvFyhSv_xVhy2VassG6HmI69_DwnKCZ2FHbnf7nyG_bnk_wpm79rV6nVicRxqyzum7D3exS3Z4Zsdd5SsbbHi6CPd6GjlhaLpnd1Ie3D887Xc0buBVuIvdlc8TKHKhasR8bjTATd8ScdczGITNqT8--bSgXUcF4ybBuU-UaKtUTYT6X89om2rzP-r3eVXtk9s-6jDYjGtvI9Z2VmyVUTSZf_up-karzLMF7tkl-Wbe2R9SA-ZbLbaI3PYxZ_mrrvFXe__Z83lNSbuFuSboT63lnWPH1RV_enmDsE3gkneyEg6uBl5WtotRyUSLsu87cyDDI0_TS12VMGUgJEJGnsZo2faFVTOjaW4jarVaFVc0_-dDFf6BK8Y7JMymCFb48H63bNkmavXR5ZhvMfcE5UZgycim3tIogoKd_IZwvwl0TsNhi_P9d5f5Az1VdX1EntLPl5pCEUNNcqWL4FPRBX8unxn7OdfBFn5niKkRtbW8wBXBoDYKeaQWDcuRElAQvXsJlNodAUZ7Cb0GheiemcTufCaYM-rMM4zvoZ75oFr8a0N2HCKW2voQ7ER2t7Ygo8GT9FB0iOWWDY72CfVU8gcbZdfXlanLePSIiIUjntzUAtEaYuiZOjVILfm-I22IeTUy-xDe7YfLShZE2mWlUzSMmsQStETPOeNLlFEg2MwuwYFcHcs14gsonPTPGSTIxzi_KggMRbqF8ptnUO2qCskIIwzGAONNUHPuC3vfP7d0U-Drc0zOBEVxN5114_XVxzhZ7_mryGUb5ecKSSZR94FE8OEgMtOCojf94R3DMPgeIJOXaaF8aG1TMsGa9mzlCZzNKKtF6epxDEe4RO26z8Yz8U5p-Och_6coV-JshF1rXkxZWrfsmwdisbJhhthgu8BzJsVphuMrS6bnsQ_x2FDxhlO7wZRBwlEQ4r_twV90jz7HrJh5OTSNtQq6_DjHLvAtuZQ3gpUrVLyMFPpn0mk7j02iYJBBUJn7_kPqHF6G26UNBT7l6drzey7wKzrgse0jJwg0wFSanIcwpPj_La7G-JnR9MBE6kZQeuSaKEUWTUTctx1Co--uVyEGNhY4B7Ad26Fvomez8f5rtI03XqMnrhWp417Wq2bwo0cftwk44Z93gxQDSVNHkwWgWBE0V2dycZnDvdySz3je--NI9PxpXWNzuyCq16cLTqdpcLqkoYro-veP4gMkF3ylbM3C7A5RCg6uujvpi1db59EnXJD3WBbqcvpg1mrLfHH8_7qW_8eN4XAxAgYFMajakz_uMuVD2IjZiCKoP5PXfZ7eLdBrw_h_1-2uG1Og8hvtKKoz2bAX4Jw3njPNWUu_rPUmKBtRFD6WSsCnuI1QHhsm4Ji83NgSlSRskMwrPJvEDLQOlX_wG8vSyS2J_4dai88Fo8F0oOf8o5XFTofrolJB-nFyN[diaram]

== Достигнутые цели

* Более четкое понимание того, чем занимаются DE
* Осознание вариантов своего места в этой профессии
* Сформирована и зафиксирована цель на этих курсах: +
  достичь необходимого умения и навыков, которые, в дополнение к моим знаниям и опыту, помогут мне перейти на более высокий уровень профессионализма и бОльшую востребованность как специалиста
