= Домашнее задание 1

== Оформление этого ДЗ

Использовал предпочитаемый мной на сегодняшний день формат ведения документации: *_asciidoc+plantuml+git_*

== Исходная постановка

[source]
----
Домашнее задание: анализ рынка Инженер Данных: РФ, USA, EU
Топ потребностей бизнеса, ключевые технологии и умения
Понять для себя, где и чем бы вам хотелось заниматься
Фиксация целей на процесс обучения
Рекомендуем сдать до: 03.12.2019
----

== Решение

* После прослушивания вводной лекции по DE прочитал еще несколько статей и примерно составил впечатление о том
  ** что на сегодняшний день представляет из себя эта профессия
  ** с какими инструментами там работают
  ** какие задачи решают
  ** какие умения требуются
* Выделил в структурную схему WBS на основе материалов лекции
  ** Топ потребностей бизнеса, для которых нужны DE
  ** Ключевые технологии и умения
* Окинул ее взглядом, много думал (С)
* На основании предыдущего пункта добавил в эту структуру собственно домашее задание

=== Схема WBS

image:http://www.plantuml.com/plantuml/svg/fLXVKrFN5ttFfpZ30wD8G1J5oVpuwOZEo0pMLcrz01ykoHMYuOP9RhI-0H7R3bQqqccdQYtzC-rZ35u98OIlSCutwbftdnilrmIdseTExZvxh_rdhxFtmNDbtodvzsRBgLJMzNotDEywERUK6bTwGxTrIzVCjtfF1pfGUblNz1jTmsT31odNordTLC6TmvVoYukguDxoKmDA_sfMO1pW_qtTI0qCgF_rGxla_r-bbNvfbW1JrmspOfRD-g0ogxeDrK3lwZOaZvH-RTR48PqX2cW-egv0PUVTx9qGwaS8SKJTFT4swqet56BVDsjcHVGN2vNoGVKcb9lC8ms_xGFcp4moIZ6J3JhNDO3Y-AqEM0t4JqM2mugMkpZULcR9hE4Ju3DUd_uvRa0WgkuXgjK-MCBqbxIkq_a-y0BzXjcB0S1sgC92GXuWwcLTWuIYgRntnyrDUlpazt4Lcc-Rgjv5aH0hKz9ru8RW-Ds0UTDKLTy5ntUKwytbFTSjzLaNV-0C3M623DowkLsSBG_bYfMXYcEHjdGRUksG0wqPRtgwW4Woyxw_MCuC3yVqX-ywMSVBvjtoyDciuxjpnTBzSRe-TWr2B-lsby65xBp8ed3wSsuvMneVKOIzUPDXI9NO9gGpUeAYP57KoF6E-Bbvn892DoRy2_LOma4pUR31nh3sQhGZ-vkjWXogvY4eUB9pyWFB4nBa8Po-2-Kd56FV5kOjt0Hg9EOQQ6OP9tinwIOQrG9sJ8zNXSsp-4ts_zqvz5doNJA3BGB3mtwzvgMH2dHdnecniK_bnc_wpnxWwlHeD_3QXw5dF5IpZIlNOirORKo0PGP670KnaiL5skc2htZFqfmCc16yC2nMMFmwVodpFN58LK02PqT2giSpkOInTQd2OQUcfoFwpiyFbIh3malBt_jddPBhZ8_qb_rnEVXAvFs--xL_aBm9qi9Rc_pac41_Zfywx99J_mNraK4TqOwU-g3w9cS9QhkIrgyuPKaqpCmg_h-bJfmUwMuVI5ClVjcBBwVLcT4pdqOPnlQFVjB3myanDNQoHtGxuCM6gKhx1z5Uyfx9uQTG0wieW1BZ8FN978feRHvZfcE-wph909L0flFl_80_wjCde6X5jWLw1yZa4mU135YQl292AAvps56NlxXL44-RgybyesiPDJbPl3uOhZfy1nAFx9V128NtzYqNe72Y8MxrRYQXCAWchbw6rHExJAZOu1w1x3dvp9f7Ca5xAXJG3M1jShfnAK6o9J1KDW_4Xw1tZvHXRGuGaiKAE6K8fbiP6jdZRf69oGks4GBkHmn95ZX36u10kSPczipDLYLoo4Qo7ZYsmn0p852yHD8lJatQS8r_5vvWLWP4PUhq3qMsEhJU9caxEzqESI3k2tsf3bM0I4aOQsSVxii3HKOkpsd1mKlUTQjXhLjkSgrnGccdFUgocyixi7b69sZH6bEictL474HhVwAGpzwvvcFyB0pQigPxERdgEeMqdrzmWPFWGIt90_O3lvjCGBI8yH5Te17vd-cQOuV_M_ZYf9SHRTiHtSqcy1-pcBekFZZ6LaEBNThQddB_CQoeaNmIC0kPx2m9p6MzupJsr9pnE9zcdR9Rva7inBuWeN7jYoavYrbzLhJIwEa8sPL5j-Ju-Q8dKEg2U_VAelqTGolUykzXQV3OBHGN5_2aZXfQhEJKvmN7lrKiBPIJWPxFpoa6gwuNYuLojpJK3U3E5olbl3Tty5nbZivuA0cRrqAjM66IzM6C-A-aHz2m7KXClaIs4yM5nGhtetsl9GEwFAMEgVEJRAF5DklohiP8v_DacOmrwuXhYpESNGmRtR8l-xey8PFl_XvFVdfvHfme6_8iueJubLjVXHC8XRE9lmdmKz4NDnV71sC1X90wzg12U4T435m9_wZrctorHEaIcok14qz2sIVVYSTCeygq9Ke9EhfTTgU6LxH100I_B5ab7dxKh8UpmaA_eGonS-SndqwtDymIJ7b_U2ZZaS1CRcXeA1KzTQE99rTPqN-uvEBcZ8txd_TBhkbiVYu7GigRJJgHPaJlIYX_07Kh6Fbs62JiQnomNG3jDPq89KjarFiwh7BdZonrvEBKTLoDDFu34Lz4KI2dz_d361kCkTSVagmzna8tbMW-yQiUeSlwanQrH8YHnd1vJHC3iI7qlEtSTP8E1XNh9CDLfkGwq8GeH06P7yVe7xiFiWuiARdjU1RUrMeg-ZkAxqKRmtOqCfHPXPZ280hXmerB_wsEXrNHre8NSINsTWzWPST-j77njKDhyu3n9UHa7zCdZAcoE3CUxm5l91E1KaG4lOcT_bHlf6pM74tCDtuBPGBmpTU8xcoYqVMGlIAJNIdnjIYMaRV3AM2MGsQoxl9cKx65ebz2rvOiuC_snmR3JHlLG021O5z2qL8_78H-myrPYr6bsmYXIVn9r9sOkXqzwwK9yeyxbeghuLEw2Xls2kwuhLFdN2-7Vtlw5m00[diaram]

== Достигнутые цели

* Более четкое понимание того, чем занимаются DE
* Осознание вариантов своего места в этой профессии
* Сформирована и зафиксирована цель на этих курсах: +
  достичь необходимого умения и навыков, которые, в дополнение к моим знаниям и опыту, помогут мне перейти на более высокий уровень профессионализма и бОльшую востребованность как специалиста
