= Домашнее задание 1

== Оформление этого ДЗ

Использовал предпочитаемый мной на сегодняшний день формат ведения документации: *_asciidoc+plantuml+git_*

== Исходная постановка

[source]
----
Домашнее задание: анализ рынка Инженер Данных: РФ, USA, EU
Топ потребностей бизнеса, ключевые технологии и умения
Понять для себя, где и чем бы вам хотелось заниматься
Фиксация целей на процесс обучения
Рекомендуем сдать до: 03.12.2019
----

== Решение

* После прослушивания вводной лекции по DE прочитал еще несколько статей и примерно составил впечатление о том
  ** что на сегодняшний день представляет из себя эта профессия
  ** с какими инструментами там работают
  ** какие задачи решают
  ** какие умения требуются
* Выделил в структурную схему WBS на основе материалов лекции
  ** Топ потребностей бизнеса, для которых нужны DE
  ** Ключевые технологии и умения
* Окинул ее взглядом, много думал (С)
* На основании предыдущего пункта добавил в эту структуру собственно домашее задание

=== Схема WBS

image:http://www.plantuml.com/plantuml/svg/fLZVKnDN57xFNt671wP58g8eJgPKnnypCeErLLiVm8SbMI4QTfbae_MDW6WxMB4jJZlLrbBRQHzZS2M44Fw5U_-ZVj-UcxYi6vtMFZZPSy_vpe_ptNCFFLq9d79mPxQIoUHTBt3BywvJSCkP2QKtT4UtTTrye_Tqg4EbjtLTlz9rV3Prc76zWjNDbDmvVAd0NrGbzqQG6LBwDxCCun3_jdGpCpIaFXc4TZduL6ML_jKi0QQXcsRPrCpwi3AhkWFLKE_g3YGFbNvfrkXGd24AQ3waha3bvztyhGZg2OGuekwUQ9jrfPiAiU-RDRCi-ekbQkMWUWlABUQHXT_E0NDc9XbbcCa6dUiwG77yMeUi1kAd8i5XHSjT76yhisJMy0dm6Mz0_nmt811Lzn3LwW0iOVfBLZVeV1zueNx5xCK0O3jKOI4X3n5rJTSfWMYgwDro2vCUF_bzH4NcssP5xw98Y9KfwGPm8t3yRiAyPLRKm3adS9JhpHKzroqFM1SlSCQ6C444RjtSz6ShXmj-zN3LiKXRkWEzJiI1zemtFLr29Bdv85Yiv4P6OleZjvsyu-MBRcNaLDu9t3c_V7U2hWzTWT3BkuCLS24_Bx9kE8C5jv8lJumgmbw_Bc6mIcmJqXaxIb6oA6hqI4_yr3naGQ4R4_w5UYpXe9Kys61ZM7irrfFzpLP13bLp7nGyrZlv8IeF2N8VJj-4yXEAiMyBynfkGZKQSmqqKyF9NaowYKQrWHtNmrLXyon-Y_r_SmvzbdoNp62BmF2eNozvQQG2wSmuEZx-eTpuNV_P1roT64i3hxyVUiP3DJkuSctMZDN61AWnCE8eY94iBj9E2hxYFSjoCc16yCAmM513Jlobp7V48LK12PmT2QaHp-G2njQ5AeUTcfxkqdT-_d2vEYAyjFozUyefkyx4w60bc923hqG-6BXV1mV9co0jl76GrJWcq9yZnzzroQd_ZFh8e85enuw_LtsJimIrNSxgvvoo91fcvWh-tL97JuocsuVIrFDVzkFB2NLoxEG7KWQn_QCVz_5mR5oD7-iJtGvuiM5MfFt3Ykb00ydXfr03Jr489SP1wfCv5D7QFC9CntpN3P81Ag5Cvp_u0N_Kfqz0qQh6akaT8eDF70GoO6doF4AWkC5XHrqPqqs5U3fycim3NS-foKd_wd3qrE4xb7ZaVHacYXsLoA-PiPneYbkzcqie3Akpbo_2wh5zJAZOv3i2sLFocJNloWJjUw60RW9hazEDZn8aMm93PNDFV0XwUgGCQtE8a2nMo2b3CDtEqSWUfqKc9i_OHWZuFd98ei0vsW04odKsiszkjYfTXsmawu5ZEmmn0q9UOyazvDGKcoVcs-W4ip8aAbEdVoYorP7rDadRUzFj40VYlj2Nwb05Y9I4iVRUmtrPK6JayfmM7BpWNMeDwscvoRN62QMzzgYBRg7emEP7Ea6BrfXYmwmZuh3xx9yj5VEthWGOFml3jgpPVaukkquf6nGNNE0aU51Fye3zmEyM4n0jOFolBi28_C-bvjZZ_nQ-EEbbHDjsTEzc2_YFM4pT41ySOwkHnIvjRK_v_abOqaYk1Cn29ZjB0dDvtd4QMpLdFCwdMQVYLd0GFx4R93IkV35ry0ooptoHzbP7o2ujkcKdAFgUGAbpxkrBY_Pt3Cs_4Tp1ey5Zj-GlBc2bxZRKhnRKvoKdkE6N5oh9GCyKvnI3LLTzlrH9IqDT0-wyNwqKlRc3vohtyOo7ah1vRTIA5IPPxyU8_rnw10tRWSJaIsHxrbzOhF9zjFjQCg2BK-gGEZF9DbfiiovxDKOwrvCQ6MlM4TSMPtZKHJQwRJVxXgoGoRq_VUMdRs4RSA3AEOpshqGC2UrmrnrIm39fjZXNGCrahOX8sSvoShzPcsH7H_HlRI8ioRiWOS_G7gG0sbP7WYNc_BOAAzJxCq1zT7xgAfgNnNyerRDk4F8-Dhkibyeon2P2xlkd3hSS43Uf4hz1_6fOT3kWNz6XReiGbuxXaaY9AzjKH5GtdTjEqi6mOfda-iizNWSQmNdEHk5nbh6CdmziFdRuiYPKLJAFSHQnQQNxrmyN6Xl2TfVJogn2J67OZU3SjGl_hOplAg8jHSZzAhPSXh2oSwdx9E1h9whlFSQNa9Dxp9umI1or0U6vWk26C14eMHxm0N-11tqZ8qdpwW0kDeDPAwRCdQJ9fgJyqTiGwaOocUKINfjYkP8xN5nCBU8bgouxXUeDFAKtuXSBGF6dCBtT1BFhdEGcVzJR1gz6AzGARA8IrA8fdJdjUWNyFuT_0G00[diaram]

== Достигнутые цели

* Более четкое понимание того, чем занимаются DE
* Осознание вариантов своего места в этой профессии
* Сформирована и зафиксирована цель на этих курсах: +
  достичь необходимого умения и навыков, которые, в дополнение к моим знаниям и опыту, помогут мне перейти на более высокий уровень профессионализма и бОльшую востребованность как специалиста
