= Домашнее задание 1

== Оформление этого ДЗ

Использовал предпочитаемый мной на сегодняшний день формат ведения документации: *_asciidoc+plantuml+git_*

== Исходная постановка

[source]
----
Домашнее задание: анализ рынка Инженер Данных: РФ, USA, EU
Топ потребностей бизнеса, ключевые технологии и умения
Понять для себя, где и чем бы вам хотелось заниматься
Фиксация целей на процесс обучения
Рекомендуем сдать до: 03.12.2019
----

== Решение

* После прослушивания вводной лекции по DE прочитал еще несколько статей и примерно составил впечатление о том
  ** что на сегодняшний день представляет из себя эта профессия
  ** с какими инструментами там работают
  ** какие задачи решают
  ** какие умения требуются
* Выделил в структурную схему WBS на основе материалов лекции
  ** Топ потребностей бизнеса, для которых нужны DE
  ** Ключевые технологии и умения
* Окинул ее взглядом, много думал (С)
* На основании предыдущего пункта добавил в эту структуру собственно домашее задание

=== Схема WBS

image:http://www.plantuml.com/plantuml/svg/fLZVKnDN57xFNt671qQHY2YAaodL4PsH6Qojsle0FYp92j6mOPADrZSWOjl1YbOwxLIjfJ_6FiRWIWWX_0lt_aVzlZrtux8cEDK-TBBddlET7-UxvrmyM_QTadztffnAPLtFTqjphfDpIwanfTTrMxTqpNolTtMW0wMtT4s_qJLyDdIGShsSrKqLt5byAR-ue0hkJJyreFJlPXd60VxVr8tKm83wh1_Q9VzpbLRwXLa4J5qtpB9PCck3ogpeDbG3lQFRa3nK-hLP5OTqXYYW-P2w0fMTSxEtGwYV8SGHTNT5swmftL28VS-iccNHNoXKollLcr1kCeyq_BRtcJCpoIZ5JDRfNDS0YkEtEc0r43yL2GuhMkxWU4kPHREAJu1FUttwrxW1WQYwYwXM-c09qz_IkaxdUy0Bz1jcBmO0swOA2mbvWAYNT0qIYYRptcqtD-7naz_7L6Y-PQfw1qL2h4n9ru4RWkDt0-PDKrLzvntVKQutc_TSjzHdNVo5CpI42J9mw-PMSQPyD5Ui7Aqu5cbJjw7N3ZdGclQcfWg893Fd-mlbpD1GJ7_eZfDrl6pUBG-ToJg-EriitHkZwoDN8VIoRdyPNCZEYImAfp_dbhEbiM55s1it68PKYMr2EYF7AKeMHGqVwuYVcOSiA7HZmdzGZqKSD9C7wsmCQwz6Eh9NR1NaK3KFGC4JdPEVmlAG80_Wz5qelw0OUxOmR-4cKCCnrq0pIpZPZKatqAWMi6Dwl2fidiLlil_lpg7Fak-G6MmH61xswpKlZLIWEpEEZuv-AZV-q7_t05UdHhg1rpuCFUsXccrSkHPhncfZ0YmnCE8eY94iBj9s5tp5UvRcPC2Cu8LXiSBYr_bBcH-9Gwe24ZZR4b8zdib5ZAsB5GuxDJKLqNTkxcYfCYIyjFozTyOfkSxOS7_P7vE3RqJUxxlV-ll9co0jlBN9Juu9zEVOoOCkEVMVKnyPr17joCaFgczmbg2sosdzabEMHCFChEB_c-hugU7kze4qzSBNlVXoIfqUEVrfb65i_-h7FJoS65MZ9tf4jmrUh9kgj7yGxINlcHn-2ZMmYW8eCGvIdyoXYDRc4MOwvhkkamnG2MGw_yaF-AC-VGAALcHReBU1J3vn4CY0fSbB8eJYEeSTTVcBMmNnjBcQp7Uwbb4J4yLhW-6gmtSWySX-6HGK6PLlkG254mrngtSo2OL1DNxb4gmUssL2nGRt26JFo6VMF989sXEXW6u0QuFJZKi9aas1eRAvBpu4lNka36jZW90iLi0fGp3Toj387dUBJ4oUiuqGS3zoIAB06TWG1CerDhDdRb5Lh4CsalN0iHs6c061uYMIVd5gqePh_8Vm1BCo82fJftyeijMXzHP9szdfTeW3SK_eItMe4aHAWbWx-t1F7YWoSdbE2mvUygvR3MlTSfDhZHDAE-rHbznSte7DKpf1YrQPOjsi8U8WMllZXNpszbKVusT-q9OrtSl95TSffFtyl0kS10zgIHwm7_ZTP0AYHOoFw0ADoFzCrnmx_D_45oUzZ6ZRZkXkDe7_YCNKTV71CROIMkpGrlQK-uzXIIFbIS0iPBAZ93INzOxJs5DpskDycd7ARfa7iHFxWeJ6rQycvInczKKnajgd8sIN5zoIu-UBda2fy-wTomlsTmojUDE_YwN1OxTGN9Z7apfgQB6IKryM7FzciJHVJWPwBZ-h6AowLYmMojtIKDU1ErUibFFUxFvpbJayxQ4aR5uBjMA5ITO7CUA_b1v1mtOWCVaIsOuNvnSgt8_slPOCwDAaEgBEJR2D5jkioRiQ8vtFaoKorgmXhatES7OnR7JBlkphyeHClljxFFdfvIbnecp8iuWJubTkVHLE81JE9lucm4z5NznS71-8XH12wjY32k4T4Z5m9Vp3rc_orIBf2ZPN0YUUXB97lXEFcKQLQKkK4dHqk-nE3QzeWm08VacoIZpyg5aFPuM5VaCPOkVEOpwTRg-RHPZo_l1GngFCWcY0lgA-QCizLg5pRhYuBGFZykVbaZiwav_DWOtoO9Csf1dEk_h9Np_TgaMo7GG9-ngdQnT0UqV7GyaYwVI-3alS-GjB7RemUGtt8et_mCBdZC8M-ttoCCO6O-xrLoGBZvcGL8aF9txL8tJPVTAVbWWnpnWkxsXY6ZQ4cxUSEqxImQ1YdMIooeXS0nh1USvEcKSnxiSkW-m2oqYkEfw55xMQYlw8ucFHnh0LpGjbLXWcMnM5SFxwnVzNnuEgQ6l1MxWSUxW7iB8pFrgt-DgcjRdF-19oie_f4yPKMPnfZvU0rv69G2aYWjx0Gd-YrrCsQyubvXk_WdBz-U1hH1SsqUXwo5wHoQAK-5eKoxpRvWWmIo4pMNTviAdODj4le6jB5l1d-sE3uPgDQY20GB3Fe6YZ7mn2l-7QhCMeqcr-q2J-7kfEJDsEtlJI1FcN7Kl5bV0TNOKDUmLtNDMfiwwNmpyy_GS0[diaram]

== Достигнутые цели

* Более четкое понимание того, чем занимаются DE
* Осознание вариантов своего места в этой профессии
* Сформирована и зафиксирована цель на этих курсах: +
  достичь необходимого умения и навыков, которые, в дополнение к моим знаниям и опыту, помогут мне перейти на более высокий уровень профессионализма и бОльшую востребованность как специалиста
