= Домашнее задание 1

== Оформление этого ДЗ

Использовал предпочитаемый мной на сегодняшний день формат ведения документации: *_asciidoc+plantuml+git_*

== Исходная постановка

[source]
----
Домашнее задание: анализ рынка Инженер Данных: РФ, USA, EU
Топ потребностей бизнеса, ключевые технологии и умения
Понять для себя, где и чем бы вам хотелось заниматься
Фиксация целей на процесс обучения
Рекомендуем сдать до: 03.12.2019
----

== Решение

* После прослушивания вводной лекции по DE прочитал еще несколько статей и примерно составил впечатление о том
  ** что на сегодняшний день представляет из себя эта профессия
  ** с какими инструментами там работают
  ** какие задачи решают
  ** какие умения требуются
* Выделил в структурную схему WBS на основе материалов лекции
  ** Топ потребностей бизнеса, для которых нужны DE
  ** Ключевые технологии и умения
* Окинул ее взглядом, много думал (С)
* На основании предыдущего пункта добавил в эту структуру собственно домашее задание

=== Схема WBS

image:hhttp://www.plantuml.com/plantuml/svg/fLTTKrFT5RxFhzZZ1TDY8g8eJgPKnuyPcS7QggqNuCKXEK8q94noelME4C5si69Rd7RKrW_RQIz3uCWXXF0Nzlv7xxEUlPFtS4nqtbSl7CxwM7jzFFlPAvUgWLS97izNKwcSNmhyogBlvVrAQahfBTtL7TqqVzA7EjIXqdkwgNTr4v-H3bD-AUziKqL_0LygA2-hedy_I8qg_Swiw4Zf8yI8J5stnRy5txRuGn3fVIKQMXoOvmZUfS61Ca_XszHxfg5EffGwSTKBFEMN5Webtw-SaE3_Dgl8B3Ih21UbHaVLhqQGIYNujSee_Izwjn1yrTJDPbgPDTs5QQWFT1UIvqflcmrMmqfG8YoVYwqDbLlqSmyPwXM4K8djeRKscqhAwkeZis5MhVroiLOzRjvceMXI1kTsZxbBssoxKbB9bXokcmWAzMSTIglD2WqbEBtG4wZtb5an6_X4yBdI2VtFk0C2qVGGMQsXHUBwEgDRSlWHueLwLwft3kYzc4WZ8G-HTLqtHGBHJA7qqCzFb_39xzEAxXY6J4bobP9qYwEDpTSqaeDoHto23WDXWKZS7VEWF5yzbI_NJjKy5sb7Ts7N9S0wSwNPsI8ooIu6mN8rEpOMinzxvEMyKgxWLySkvhp0NoXNdap9qITlGrZA-IDLO26tQ6MzT4RoVZLNcHfN4lRUFQR1BicOKCx46OeIJL7Zf_lYDm1fYwN7XFz5FrQWQ2SLMp8OwRsQwCl-nzaUYgbP1mJFzZL_a_OG8EiuzCTK_e5c7Bd6VCOneHgF7OrefWxDOKpw0OFg87RS3bT5XkVYjtdt-dhOxn9Y8JDe0k6SrpOl3Jim61bd9YU_5nllzN-615Vd9mO5Rtuxz5m9tUpYodMaPzBjj99xQMb6GOnYSP7s1yHNSiyomWpW25uOD8lDRybVolo5SG1LX4ISVPjIArx9TN3YzPemgPgTxS5tSV5KfJPcSUdm--IYL_6zgV6HQZ1b5N-myf70_sDm7Bn9qBudaTM59Z2Vq-U6Nd9d_rRiTLluLKsS-wRv1t99swncz3kohC1sspJm_uuwStvyi7zeXthjzyFmSbvTcBZmdP11Rl_NBuUSS7PIJPuTajq-SB65Kpd-j99oUCrNyQU51jwv44QI1w4Fv8Y8j-O5E1tyhbi21fY4bfq_oWVE4tkUkKslEb-RVOaSaVj3Hx3kNUnIt1AoeorfEbB8fojFatcccrarFLs-a-PJX-_GvSFt9SqeZYe_ym4a9Y9xh3x89WpIwigj6_1wQHyJ6aRoZa3sXdX6pvtCfVbN2m4TPQNbRLAGKDIE3IF6vgazWz67POgqFepQa1_v0eUaoawMJbOzA3FhyfPZZFW-WYIbmLduI10ODsMOGsjpNUaTo47k4cwE3C41eU8buho4DQtFA_DdQimwdPeiFHguhRWttP4u8XvP-BhLHuAm9P9h_pqySWiAAPTwU91uTNTW3vi3QdFN6XgHziUZRlZvWWUVlyiX6D66bDWocyWux3txLug5tCFR0UXdAUtQcXbso2tVAsQ2mfAFE0aSD9Cuq1qsgyq2Q8KOFsyAeyH_Tc2DVVply2tTSnJjnk7kfY34l91cwXRF88sjqUE0ldQcYfmGka6wbG1LaDdP4d7dymvjRDMSAma_pNjLlmf5NECsI5ZS_jrCN4UltvITjBSwGdPpsQzuGQ5Sig7KLV_HpMNtTonQ-Nxm68-6gFrYUNa9-tfleELQNlssw0NtovMbQZBHouK5HJAzKouNlz1ISnTn5ykrQg6qS5olihy4ARxcy3gcmGuBMDTZm7zdPmGBDu44yoMglL9UMgx9--ZsjMH2DsRKINLvsewHiSqczsgXT5bFwe9OiucyTeJ3EKKPTCTjzYsxGYRt_c4h_wYoQ5FG7927CVu64H8wSkScq7L8cYyivD4pkrOGb9sCC7TiRUAEFgg-t4Ia9LyB2Nz9xTc0W6xK5An8pL-QI8VwFmFKBwxDtC7mClY7Lhtj9M7VnwY7UdQMAKP8UUXF7Tbo0DoaIVm6oLVBHNS4lSlxrX4XBopJ1P0ILpRYJLCFl4TUye2q8klm-hDLSieHWuiUWvB7cRICFv-vUXpvIa_4L96FHKSqDNg_VcIXSIdizJ2jp1gpb46v3AxUlVxJslYr9hfMXB9VnPRB45wEbtfF0hxssT-dabz2JkoXUWbZ6j8R07w5hBefXS38uK0Uy4zuqBTIjcYvEYpNSJ2BOScoaqGob04_UbiMkfGvBcTw7H7RAxalYukf4vVITRjJg3xXARqLkrWC57yA1uyRmTmwvshZZtetu3MkK0tui0LridJgab_AFvwl_W00[diaram]

== Достигнутые цели

* Более четкое понимание того, чем занимаются DE
* Осознание вариантов своего места в этой профессии
* Сформирована и зафиксирована цель на этих курсах: +
  достичь необходимого умения и навыков, которые, в дополнение к моим знаниям и опыту, помогут мне перейти на более высокий уровень профессионализма и бОльшую востребованность как специалиста
