= Проект выпускника курсов OTUS Data engineering Клюсы А.Ю.

== Постановка задачи

== Примечания

=== Установка и настройка

* docker-compose up

==== streamsets

* location locahost: 18630
* credentials
** admin/admin

==== cloudera-quickstart

https://github.com/emirkorkmaz/cloudera-quickstart-docker-compose

* location: localhost
** 8020   # HDFS 
** 22     # SSH
** 7180   # Cloudera Manager
** 8888   # Hue
** 11000  # Oozie
** 50070  # HDFS Rest Namenode
** 50075  # HDFS Rest Datanode
** 2181   # Zookeeper
** 8088   # YARN Resource Manager
** 19888  # MapReduce Job History
** 50030  # MapReduce Job Tracker
** 8983   # Solr
** 16000  # Sqoop Metastore
** 8042   # YARN Node Manager
** 60010  # HBase Master
** 60030  # HBase Region
** 9090   # HBase Thrift
** 8080   # HBase Rest
** 7077   # Spark Master
* credentials
** claudera manager: admin/admin
** hue: claudera/claudera

===== Cloudera manager

If necessary then +

[source, bash]
----
docker ps -a
docker attach container-id
/home/cloudera/cloudera-manager --express --force
----

=== Загрузка информации из публичного источника (rss, rest, иное)

Возможно, использовать стримсет и его коннекторы

https://hub.docker.com/r/streamsets/datacollector/

https://rapidapi.com/collection/top-weather-apis?utm_source=google&utm_medium=cpc&utm_campaign=1674315309_64978333346&utm_term=weather%20api%20free_b&utm_content=&gclid=Cj0KCQjwpfHzBRCiARIsAHHzyZoekUFE3eg8G3S297tNcOwMg8UkDKHFF32FnGOIW3XMhEMc6_nv7BkaAvziEALw_wcB

==== Источник openweathermap.org

https://openweathermap.org/

api.openweathermap.org/data/2.5/weather?q={city name},{state},{country code}&appid={your api key}

https://api.openweathermap.org/data/2.5/weather?q=Odessa,ua&appid=d12dd3e0376f206595b3a0660911c2dc


* Выбираем погоду в 50 пунктах вокруг Одессы и находим мин/макс температуру +
https://api.openweathermap.org/data/2.5/find?lat=46.4859841&lon=30.7249136&cnt=50&appid=d12dd3e0376f206595b3a0660911c2dc

