@startuml Схема процесса

skinparam ComponentStyle uml2

' left to right direction
' top to bottom direction

centerheader
= Тема проекта: Загрузка, хранение и анализ публично доступной информации
endheader

legend top left
  Схема
endlegend

cloud "Источник (rest API)" as cloud_source #LightBlue {
}

note right of cloud_source
    Внешние данные
    с какого-либо публичного источника
end note

Actor "Внешний\nПользователь" as extuser

frame "Хранилище\nтипа Data Lake" as frame_dlstor {

    frame "Витрины" as frame_dlstor_dm #Gold {
        frame "Представления" as views_dm {
            component report_1 [
                Представление1
            ]
            component report_2 [
                Представление2
            ]
        }
        component batch_dm_refresh [
            **Batch**
            ----
            Обновление отчетов
            ----
            Периодичность: 
        ]
    }

    frame "Обработанные данные" as frame_dlstor_stage #LightGreen {
        database "Реляционная БД\n**Vertica**" as db_stage #Pink {
            component anchor_model_dwh [
                Якорная модель хранилища
            ]
        }
        component batch_stage_refresh [
            **StreamSets + Spark + scala**
            ----
            PipeLine SilverLayer
            Batch: spark + scala
            Оперативное обновление stage-данных
        ]
    }

    frame "Сырые данные" as frame_dlstor_raw #LightGray {
        database "NoSql БД Типа Hive" as db_raw #Pink {
            component raw_data [
                Сырые данные
            ]
        }
        component batch_raw_load [
            **StreamSets**
            ----
            PipeLine BronzeLayer
            Загрузка сырых данных
        ]
    }

    cloud_source --> batch_raw_load
    batch_raw_load --> db_raw

    db_raw --> db_stage

    db_stage --> views_dm

}
@enduml