= Резюме

== Обо мне

* Клюса Анатолий Юрьевич
** Год рождения 1973
** Семейное положение: женат

=== Контакты

[cols=2]
|===
| Телефон
| +380 50 316 55 17
| Telegram
| @a40325280
| Email
| tolicheg@gmail.com
|===


== Образование

Высшее

* Учебное заведение: Одесский Политехнический Институт (1991-1995)
** Факультет Автоматики и Вычислительной Техники
** Специальность: Вычислительные машины, комплексы, системы и сети

== Дополнительное образование

* Курсы по администрированию Оракл
** Киев, BMS Consulting
* OTUS
** Data Engineer, сертификат можно посмотреть
   link:https://otus.ru/certificate/f15ed8abf74d4ab0a1ee2ce344486845/[здесь]

== Личные качества

Бесконфликтный, инициативный в плане нестандартных идей и предложений.

Веду здоровый образ жизни, не пью, не курю, занимаюсь аштанга-йогой.

== Опыт работы

* 1994-1995 - Одесский порт
** должность инженер-программист
* 1995-2003 - Одесский порт
** должность Инженер по АСУП сектора эксплуатации информационных систем вычислительного центра
* 2003-2008 - Одесский порт
** должность Инженер-программист
* 2008-2013 - Одесский Филиал Аминистрации Морских Портов Украины
** должность Ведущий инженер по компьютерным системам отдела администрирования инфраструктуры службы информационных технологий
** 2013-настоящее время - ООО «ППЛ 33-35»
** должность Инженер по компьютерным системам

== Знания, навыки

=== Разработка ПО

* Oracle SQL, PLSQL
** уровень: разработчик серверного бэкенда, опыт более 10 лет
* Java
** уровень: начальный, в основном прикладное ad-hoc програмирование, без опыта использования фреймворков
* Python
** уровень: первое знакомство, немного прикладного ad-hoc програмирования
* Scala
** уровень: изучал в рамках курса по Data Engineer, выполнял домашние задания, использовал для анализа текстовых журналов и parquet, orc-файлов
* Delphi
** уровень: разработчик бэкенда (ETL: загрузка/выгрузка данных между системами), немного разработчик фронтенда

=== БД, архитектура

* Администрирование СУБД Оракл версии 11
** опыт более 10 лет
* Построение архитектуры реляционной БД (Оракл)
** опыт около 15 лет

=== DWH, BigData

* Начальные знания после курсов Data Engineer

=== Операционные системы

* Линукс
** уровень: администрирование, средний
* Windows
** уровень: администрирование

=== Владение инструментами

* Git
* Jira
* IDE PL/SQL developer, Oracle SQL Developer, Delphi, Intellij IDE, NetBeans, PyCharm, Vs Code
* Использую в работе Oracle VirtualBox
* PlantUML
* Markdown, AsciiDoc

=== Облачные платформы и технологии

* Использование GCP в рамках первичного знакомства
* Изучение в рамках курса по Data Engineer платформы Google BigQuery +
  Мини-проект по созданию DWH на основе якорной модели

=== Идеологии

* Понимание на начальном уровне DevOps идеологии

== Участие в проектах (наиболее крупные)

=== Единая информационная система Одесского Порта

Включает автоматизацию практически всех служб и подразделений порта, а также стивидорных компаних.

* Разработка архитектуры БД (Оракл, логическая и физическая модели)
* Администрирование БД (Оракл)
* Серверный бэкенд (Оракл)
* ETL, работа с данными в различных форматах для связи со сторонними системами типа SAP, 1С и др.)
* Фронтенд (Делфи)

=== Информационная Система Портового Сообщества (ИСПС)

* Участие и консультации при разработке архитектуры БД (Оракл)
* Ответственный за администрирование серверов БД Оракл и организацию обмена данными между ними
* Администрирование ОС вышеуказанных серверов БД
* Прикладное программирование на pl/sql, java, python, bash для регулярных административных, а также ad-hoc задач.

== Личные достижения (из наиболее значимых и запомнившихся)

=== Одесский Порт (ОФ АМПУ)

* Внедрение Оракла
** Выгрузил БД из dbase3+ в оракл
** Переписал отчеты с процедурного языка на sql
** Переписал расчет хранения грузов в порту на sql-вариант

* В качестве DBA разработал и создал БД для Единой Информационной Системы Порта (ЕИС)

* Восстанавливал и чинил БД ЕИС в порту в нештатных ситуациях
  (сбои оборудования, вирус Петя и пр.)

=== Компания ППЛ33-35

* Разработал и внедрил концепцию бюджетного стендбай-сервера для оракла стандартной редакции (в этой редакции отсутствует штатная опция standby)

* Пришел в ужас от того, что получил задание на основе существующих создать и, главное, поддерживать в актуальном состоянии UML-диаграммы по работе системы в IDE astah, visual paradigm... +
В результате
** Разработал и внедрил в компании концепцию devops-документирования UML-диаграмм с поддержкой версионности на основе open-source git, markdown и PlantUML.
** Разработал и реализовал концепцию devops-документирования алгоритмов серверного бэкенда на pl/sql при помощи PlantUML: "UML in code"

* Уже как Data Engineer разработал и в настоящее время тестирую концепцию переноса накопившейся архивной информации из ACID-БД Оракл в BigData Apache Hive (parquet, orc) при помощи Streamsets для освобождения СУБД Оракл от лишней нагрузки и уменьшения стоимости хранения такой информации.

== Итого

Подводя итоги данного резюме, хочу заметить, что мое стремление к постоянству, к лояльности одной компании и одному виду деятельности последнее конфликтует с желанием развиваться, быть на пике идеологий и технологий и идти в ногу со временем, что в IT-сфере более чем естественно.

Желаю развить свои профессиональные навыки в русле современных технологий.

