= Резюме

== Обо мне

* Клюса Анатолий Юрьевич
** Год рождения 1973
** Семейное положение: женат

== Образование

Высшее

* Учебное заведение: Одесский Политехнический Институт (1991-1995)
** Факультет Автоматики и Вычислительной Техники
** Специальность: Вычислительные машины, комплексы, системы и сети

== Дополнительное образование

=== Курсы по администрированию Оракл

Киев, BMS Consulting

=== OTUS

Data Engineer

== Опыт работы

1994-1995
предприятие
Одесский порт

должность
инженер-программист

Обязанности
Программирование информационных систем, разработка архитектурных решений clipper + dbase3 +.
1995 - 2003
предприятие
Одесский порт

должность
Инженер по АСУП сектора эксплуатации информационных систем вычислительного центра

Обязанности
Программирование информационных систем, разработка архитектурных решений clipper + dbase3 +, Oracle + delphi, администрирование СУБД Оракл, Верстка газеты Одесский Портовик
2003 - 2008
предприятие
Одесский порт

должность
Инженер-программист

Обязанности
Разработка архитектурных решений Oracle + delphi, администрирование СУБД Оракл.
инженер по работе с данными (проектирование и реализация ETL между различными информационными системами, ад-hoc решения).
2008 - 2013
предприятие
ОФ АМПУ

должность
Ведущий инженер по компьютерным системам отдела администрирования инфраструктуры службы информационных технологий.

Обязанности
Администрирование СУБД Оракл, поддержка существующих информационных систем (clipper + dbase3 +, Oracle + delphi).
инженер по работе с данными (проектирование и реализация ETL между различными информационными системами, ад-hoc решения).
2013 - настоящее время
предприятие
ООО «ППЛ 33-35»

должность
Инженер по компьютерным системам

Обязанности
Администратор СУБД Оракл
инженер по работе с данными (проектирование и реализация ETL между различными информационными системами, ад-hoc решения).
Поддержка информационных систем Одесского порта (pl / sql, sql, delphi, apex, clipper)

== Участие в проектах



== Знания, навыки

=== Языки программирования

* Oracle SQL, PLSQL
** уровень: разработчик серверного бэкенда, опыт более 10 лет
* Delphi
** уровень: разработчик бэкенда (ETL: загрузка/выгрузка данных между системами), разработчик фронтенда

=== БД, архитектура

* Администрирование СУБД Оракл версии 11
** опыт более 10 лет
* Построение архитектуры реляционной БД (Оракл)
** опыт около 15 лет

=== Операционные системы

* Линукс
** уровень: администрирование, начальный
* Windows
** уровень: администрирование (сейчас не использую)

=== Владение инструментами

* Git
* Jira
* PlantUML
* Markdown
* AsciiDoc
* Остальное...

Небольшой опыт в программировании калькуляторов серии mk-52 и совместимых, некоторые навыки программирования на языках PL / 1 серии ЕС ЭВМ, ассемблер для процессоров x86, turbo pascal, vb, c, java, python, scala
Программирование информационных систем на языке Клиппер в системе dbase 3+
Программирование информационных систем (фронтенд) на языке delphi в СУБД Оракл
Программирование информационных систем (серверный бэкенд) в среде Оракл на PL / SQL
SQL (в основном диалект Оракл): написание и оптимизация запросов
Построение архитектурных решений на основе РСКБД
Администрирование СУБД Оракл версий 8-11
Начальные навыки работы дата инженера (spark, hadoop, kafka, nosql db, mpp db, elasticsearch ...)
Навыки администрирования ОС MsDos, Windows, Linux
Знание git, jira, open office, markdown, asciidoc, plantuml ...
Бесконфликтный, инициативный в плане нестандартных идей и предложений.